[target.x86_64-pc-windows-gnu]
linker = "C:/msys64/mingw64/bin/x86_64-w64-mingw32-gcc.exe"
ar = "C:/msys64/mingw64/bin/x86_64-w64-mingw32-gcc-ar.exe"

[env]
PKG_CONFIG = { value = "C:/msys64/mingw64/bin/pkg-config.exe", force = true }
PKG_CONFIG_PATH = { value = "C:/msys64/mingw64/lib/pkgconfig;C:/msys64/mingw64/share/pkgconfig", force = true }
